/**
 * Builds every head tag a page needs, for one (page, language) pair.
 *
 * This module is imported by both the runtime <Seo> component and the build
 * time prerenderer, so the static HTML and the client always agree. It must
 * stay free of browser globals.
 */

import { CONTENT } from '../i18n/content';
import {
  asset,
  Lang,
  LANGS,
  ORIGIN,
  PAGES,
  PageKey,
  urlFor,
} from '../i18n/config';
import { BUSINESS, FACILITIES, GALLERY_IMAGE_COUNT, HERO_IMAGES, ROOMS } from '../data/site';
import { imageAttrs } from './images';

export interface Alternate {
  hreflang: string;
  href: string;
}

export interface PageMeta {
  title: string;
  description: string;
  canonical: string;
  htmlLang: string;
  ogLocale: string;
  ogImage: string;
  ogImageWidth: number;
  ogImageHeight: number;
  robots: string;
  alternates: Alternate[];
  schema: Record<string, unknown>[];
  /** Hero photo to preload, when the page has one; it is the LCP element. */
  heroPreload?: { href: string; srcSet?: string; sizes: string };
}

/**
 * Social share image: a purpose-built 1200x630 JPEG. WebP is smaller, but
 * several link scrapers still handle it inconsistently, and this file is only
 * ~110 kB. Generated by scripts/convert-images.mjs.
 */
const OG_IMAGE = asset('images/og-image.jpg');
const OG_IMAGE_WIDTH = 1200;
const OG_IMAGE_HEIGHT = 630;

function alternatesFor(page: PageKey): Alternate[] {
  if (!PAGES[page].indexable) return [];
  const out: Alternate[] = LANGS.map((l) => ({
    hreflang: l,
    href: urlFor(page, l),
  }));
  // Romanian is the default: it answers for any unmatched locale.
  out.push({ hreflang: 'x-default', href: urlFor(page, 'ro') });
  return out;
}

const postalAddress = {
  '@type': 'PostalAddress',
  streetAddress: BUSINESS.streetAddress,
  addressLocality: BUSINESS.addressLocality,
  postalCode: BUSINESS.postalCode,
  addressCountry: BUSINESS.addressCountry,
};

/**
 * The LodgingBusiness entity. Emitted on every page with a stable @id so all
 * pages describe one business rather than several duplicates.
 */
function lodgingBusiness(lang: Lang): Record<string, unknown> {
  const c = CONTENT[lang];
  return {
    '@context': 'https://schema.org',
    '@type': 'LodgingBusiness',
    '@id': `${ORIGIN}/#guesthouse`,
    name: BUSINESS.name,
    alternateName: BUSINESS.alternateName,
    description: c.seo.home.description,
    url: urlFor('home', lang),
    image: OG_IMAGE,
    telephone: BUSINESS.telephone,
    email: BUSINESS.email,
    foundingDate: BUSINESS.foundingDate,
    priceRange: BUSINESS.priceRange,
    currenciesAccepted: BUSINESS.currency,
    address: postalAddress,
    geo: {
      '@type': 'GeoCoordinates',
      latitude: BUSINESS.latitude,
      longitude: BUSINESS.longitude,
    },
    hasMap: BUSINESS.mapUrl,
    amenityFeature: FACILITIES.map((f) => ({
      '@type': 'LocationFeatureSpecification',
      name: CONTENT[lang].facilities.items[f.key],
      value: true,
    })),
    knowsLanguage: [...BUSINESS.languages],
    sameAs: [BUSINESS.facebook, BUSINESS.instagram, BUSINESS.booking, BUSINESS.tripadvisor],
  };
}

function breadcrumb(page: PageKey, lang: Lang): Record<string, unknown> | null {
  if (page === 'home' || !PAGES[page].indexable) return null;
  const c = CONTENT[lang];
  const label = c.nav[page as Exclude<PageKey, 'card'>];
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: c.nav.home, item: urlFor('home', lang) },
      { '@type': 'ListItem', position: 2, name: label, item: urlFor(page, lang) },
    ],
  };
}

function pageSchema(page: PageKey, lang: Lang): Record<string, unknown>[] {
  const c = CONTENT[lang];
  switch (page) {
    case 'rooms':
      return [
        {
          '@context': 'https://schema.org',
          '@type': 'CollectionPage',
          name: c.seo.rooms.title,
          url: urlFor('rooms', lang),
          hasPart: ROOMS.map((room) => {
            const copy = c.rooms.items.find((i) => i.key === room.key);
            return {
              '@type': 'HotelRoom',
              name: copy?.title ?? room.key,
              description: copy?.description ?? '',
              image: asset(`images/${room.images[0]}`),
              offers: {
                '@type': 'Offer',
                price: room.price,
                priceCurrency: BUSINESS.currency,
                availability: 'https://schema.org/InStock',
                url: urlFor('contact', lang),
              },
              amenityFeature: Object.entries(room.facilities)
                .filter(([, on]) => on)
                .map(([k]) => ({
                  '@type': 'LocationFeatureSpecification',
                  name: c.rooms.amenities[k] ?? k,
                  value: true,
                })),
            };
          }),
        },
      ];
    case 'facilities':
      return [
        {
          '@context': 'https://schema.org',
          '@type': 'ItemList',
          name: c.seo.facilities.title,
          url: urlFor('facilities', lang),
          itemListElement: FACILITIES.map((f, i) => ({
            '@type': 'ListItem',
            position: i + 1,
            name: c.facilities.items[f.key],
          })),
        },
      ];
    case 'gallery':
      return [
        {
          '@context': 'https://schema.org',
          '@type': 'ImageGallery',
          name: c.seo.gallery.title,
          url: urlFor('gallery', lang),
          associatedMedia: Array.from({ length: Math.min(12, GALLERY_IMAGE_COUNT) }, (_, i) => ({
            '@type': 'ImageObject',
            contentUrl: asset(`images/gallery/${i + 1}.webp`),
            caption: c.gallery.photoAlt(i + 1),
          })),
        },
      ];
    case 'contact':
      return [
        {
          '@context': 'https://schema.org',
          '@type': 'ContactPage',
          name: c.seo.contact.title,
          url: urlFor('contact', lang),
          mainEntity: { '@id': `${ORIGIN}/#guesthouse` },
        },
      ];
    case 'about':
      return [
        {
          '@context': 'https://schema.org',
          '@type': 'AboutPage',
          name: c.seo.about.title,
          url: urlFor('about', lang),
          mainEntity: { '@id': `${ORIGIN}/#guesthouse` },
        },
      ];
    default:
      return [];
  }
}

export function buildMeta(page: PageKey, lang: Lang): PageMeta {
  const c = CONTENT[lang];
  const indexable = PAGES[page].indexable;
  const schema: Record<string, unknown>[] = [];

  // The business entity belongs on indexable pages only.
  if (indexable) schema.push(lodgingBusiness(lang));
  schema.push(...pageSchema(page, lang));
  const crumbs = breadcrumb(page, lang);
  if (crumbs) schema.push(crumbs);

  return {
    title: c.seo[page].title,
    description: c.seo[page].description,
    canonical: urlFor(page, lang),
    htmlLang: c.htmlLang,
    ogLocale: c.ogLocale,
    ogImage: OG_IMAGE,
    ogImageWidth: OG_IMAGE_WIDTH,
    ogImageHeight: OG_IMAGE_HEIGHT,
    robots: indexable ? 'index,follow,max-image-preview:large' : 'noindex,follow',
    alternates: alternatesFor(page),
    schema,
    heroPreload: heroPreloadFor(page),
  };
}

function heroPreloadFor(page: PageKey): PageMeta['heroPreload'] {
  const image = HERO_IMAGES[page];
  if (!image) return undefined;
  const attrs = imageAttrs(image);
  return { href: attrs.src, srcSet: attrs.srcSet, sizes: '100vw' };
}
